---
javascripts:
- base:
  - application
  - rails
  - highlight.pack
- panel:
  - jquery.markitup.pack
  - markitup.set
stylesheets:
- ie:
  - ie
- screen:
  - screen
- print:
  - print
- panel:
  - panel
  - textile_style
  - markitup_style
