name: "Themis"
description: "Lorem ipsum dolor sit amet, consectetur magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
ldap: false

hoptoad: "YOUR KEY HERE"

host: "http://themis.com"

google_analytics:
  tracker_id: 'UA-12345-67'

get_clicky:
  tracker_id: '00112233'

disqus:
  account: 'themis'
