name: "RenatoCN"
description: "Desenvolvimento de software, internet, tecnologia e o resto"
ldap: false

hoptoad: "YOUR KEY HERE"

host: "http://themis.com"

google_analytics:
  tracker_id: 'UA-12345-67'

get_clicky:
  tracker_id: '00112233'

disqus:
  account: 'themis'
